My enum methods
jelduran/Advanced-Building-Blocks---Enumerables pull request #1
Opened 2020-08-20 13:47 UTC by jelduran

This is a pull request for Enumerable Methods Project in Microverse Main Curriculum, Ruby Basic Course.

It is about an own version of some of the main methods for Array and Hash Objects in Ruby language.
These are the developed methods:
my_each
my_each_with_index
my_select
my_all?
my_any?
my_none?
my_count
my_map
my_inject
multiply_els

2020-08-21 03:19 UTC, kitpao requested changes
# 👋 Hello @jelduran  and @carlos-ssh 

🌟 Good job setting your repo correctly with the new Git Flow. ✏️ I left your feedback below and on the inline comments, please check them 🔽 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [ ] Your commits are descriptive 👍 but for next time, try to follow [this guideline indicated in Pathwright for best practices](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) like starting your commits with a verb in the imperative tense

## Methods:
_In this section, you will find the differences between the original methods and your methods with some hints to fix them._
- #my_each
  - [ ] `p [1,2,3].each{ |x| x }` should return `[1, 2, 3]`, your code returns `#<Enumerator: [1, 2, 3]:my_each>` **Hint:** That is because it is returning the last line in your code `to_enum(:my_each)`, you should return what you have in your condition. The same happens in lines 9 and 19
  - [ ] **OPTIONAL** To avoid problems with the use of returns inside ifs, you can also use (this can apply to all your methods that return an enumerable when there is no block):
    ```
    def my_each
      return to_enum(:my_each) unless block_given? #<-- Proposed line
      
      # The rest of your logic without ifs here
      self #<-- value returned automatically
    end
    ```
  - [ ] `(1..3).my_each{ |x| print x }` should print `123`, your method prints nothing. **Hint:** Your my_each doesn't yield input when it is a range, so it is not grabbing the info.
  - [ ] **OPTIONAL** Why don't you convert the input in an array since the beginning? so you don't have to be checking if its a hash or an array or a range. 
- #my_each_with_index
  - [ ] The failed tests are due to the exact same issues mentioned in #my_each 
- #my_select
  - [ ] It has the same issue of not accepting a range
- #my_all?
  - [ ] `[3, 3, 3].my_all?(3)` should return true, your method returns false. **Hint:** That is because you forgot the case were the "pattern" is a number
- #my_any?
  - [ ] Same issue you had in #my_all
- #my_none?
  - [ ] Same issue you had in #my_all and #my_any
- #my_count
  - [ ] `(1..10).my_count` should return 10, but your method doesn't accept a range. **Hint:** you can convert the input into an array
  - [ ] `[1,2,3,3].my_count(3)` should return 2, but it returns 4 **Hint:** in the line where you use "if search", I think you wanted to return that line, but your code is returning the length
- #my_map
  - [ ] Your issues here are solved when you fix #my_each_with_index
  - [ ] **OPTIONAL** since you are not really using the index, for efficiency, you can simple use my_each
- #my_inject
  - [ ] `[1,2,3].my_inject(:+)` should return 6 (1+2+3), your method doesn't know what to do without a block Hint: Your programs need to use the symbol when it is given
- #multiply_els
  - [ ] `multiply_els [2, 4, 5]` should return 40, your method is undefined for an array **Hint:** take that method out of the module and pass the arguments manually

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-21 03:19 UTC, kitpao commented on README.md
> +This project we used Ruby to build it.
- [ ] **OPTIONAL** For grammar purposes, please use 'We used Ruby to build this project' or 'This project was built with Ruby'

2020-08-21 03:19 UTC, kitpao commented on README.md
> +git clone https://github.com/jelduran/Advanced-Building-Blocks---Enumerables.git
- [ ] **OPTIONAL** For formatting, you can use ( ` ) backquotes to indicate a line of code
```
This is written with 3 backquotes at the beginning and 3 backquotes at the end
```
This is written with `one backquote at the beginning and 1 at the end`
![image](https://user-images.githubusercontent.com/53256139/90822222-b931bc80-e2f9-11ea-8117-a28f9ae6e885.png)

2020-08-21 03:19 UTC, kitpao commented on .gitignore
> +Gemfile.lock
- [ ] Please don't ignore Gemfile and Gemfile.lock, they contain the gems and the versions you are using so that other persons can make use of your repo.

2020-08-24 03:07 UTC, kitpao requested changes
# 👋 Hi again @jelduran and @carlos-ssh 

Great job guys! almost all your tests are passing. 🥳 

✏️ Please look at these remaining tests:

- [ ] You have an issue with #my_any, please check inline comment below 🔽 
- [ ] There is another issue in #my_none and it's the same as in #my_any. 
- [ ] For my_inject, nice! now it is accepting input without a block but doesn't know what to do with an initial value. `[1,2,3].my_inject(20, :+)` should return 26 (20+1+2+3). Remember it should accept ranges too.

You are almost there! You did nicely fixing almost everything

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-24 03:07 UTC, kitpao commented on main.rb
> +      else my_all? { |item| item == pattern }
- [ ] test `[3, 1, 3].my_any?(3)` should be true, it returns false, your mistake is in these lines, I'm sure you can figure it out, it's some kind of a 'typo'

2020-08-24 11:03 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-08-24 14:10 UTC, jelduran commented
Thank you @kitpao and @mikenath223 for your reviews and great feedback!

2020-08-24 14:14 UTC, merged